<?php

/**
 * WooCommerce B2B Admin Order view
 *
 * @version 3.1.3
 */

defined( 'ABSPATH' ) || exit;

?>

<div class="wcb2b-card">
    <div class="wcb2b-card-title"><?php esc_html_e( 'WooCommerce B2B', 'woocommerce-b2b' ); ?></div>
    <div class="wcb2b-card-body">
        <div class="wcb2b-label"><?php esc_html_e( 'External invoice number', 'woocommerce-b2b' ); ?></div>

        <?php
            printf( '<p><input type="text" name="wcb2b_external_invoice_number" id="wcb2b_external_invoice_number" value="%s"></p>',
                $external_invoice_number
            );
        ?>

        <em class="wcb2b-help"><?php esc_html_e( 'Stores invoice number, generated by external software (ie: ERP).', 'woocommerce-b2b' ); ?></em>
    </div>
</div>